#!/usr/bin/env bash

DOTFILE=$(pwd)

sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

mkdir -p $HOME/Projects/.env

# Create Nginx Paths
nginx_root=$HOME/Projects/.env/nginx
nginx_path=(
  $nginx_root/cache
  $nginx_root/config
  $nginx_root/logs
  $nginx_root/pid
  $nginx_root/temp
)

mkdir -p ${nginx_path[@]}

yes | cp -rf $DOTFILE/env/nginx/nodejs.conf $nginx_root/config/

# Create MongoDB Paths
mongodb_root=$HOME/Projects/.env/mongodb
mongodb_path=(
  $mongodb_root/logs
  $mongodb_root/data
)

mkdir -p ${mongodb_path[@]}

yes | cp -rf $DOTFILE/env/dnsmasq/dnsmasq.conf /usr/local/etc/
yes | cp -rf $DOTFILE/env/mongodb/mongodb.conf /usr/local/etc/
yes | cp -rf $DOTFILE/env/nginx/nginx.conf /usr/local/etc/nginx/


if [ ! -d /etc/resolver ]; then
  mkdir -p /etc/resolver
  sudo yes | cp -rf $DOTFILE/env/dnsmasq/dev /etc/resolver/
else
  sudo yes | cp -rf $DOTFILE/env/dnsmasq/dev /etc/resolver/
fi


sleep 1
brew services start dnsmasq
brew services start mongodb
brew services start nginx
